source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

eval_gemfile(File.expand_path("../../Gemfile", __dir__))

gem 'faker'
gem "importmap-rails", "~> 1.1"
gem 'puma', '~> 5.0'
# gem 'redis', '~> 4.0'
gem 'sass-rails', '>= 6'
gem "stimulus-rails", "~> 1.2"
gem 'turbo-rails', '~> 1.4'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
