// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Load refine-rails stimulus controllers from the importmap
import { controllerDefinitions as refineControllers } from "@hammerstone/refine-rails"
window.refineControllers = refineControllers
application.load(refineControllers)
