# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: refine-rails_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '2.7.4'
        bunder: default
        bundler-cache: true
    - name: Install dependencies
      run: |
        sudo apt-get -yqq install default-libmysqlclient-dev default-mysql-client
    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_PORT: 3306
      run: |
        bin/rails db:create
        bin/rails db:schema:load
        bin/rails test

        
