name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: refine-rails_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:   
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup_dummy-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler: default
        bundler-cache: true 
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      run: |
        mysql -h 127.0.0.1 -u root 
        bundle exec rails test
      env:
        DB_PORT: 3306
        RAILS_ENV: test
      
